version: "3.8"

services:
  db:
    image: "postgres:13.3"
    container_name: "dwh"
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
  zookeeper:
    build:
      context: .
      dockerfile: ./kafka_docker/Dockerfile.zookeeper
    container_name: "zookeeper"
    ports:
      - "2181:2181"
  broker:
    build:
      context: .
      dockerfile: ./kafka_docker/Dockerfile.kafka
    container_name: "broker"
    ports:
      - "9092:9092"
    depends_on: 
      - zookeeper
  brokerMonitor:
    container_name: "broker-monitor"
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker:9092"
    depends_on:
      - broker
