# PORT:9092
FROM openjdk:11.0.11-jdk-oraclelinux7 AS zookeeper

WORKDIR /broker

RUN curl https://downloads.apache.org/kafka/2.8.0/kafka_2.13-2.8.0.tgz --output kafka.tgz

RUN mkdir kafka/
RUN tar -xzf kafka.tgz -C kafka/ --strip-components=1

EXPOSE 9092

WORKDIR /broker/kafka

RUN rm /broker/kafka/config/server.properties

COPY ./kafka_docker/server.properties /broker/kafka/config/

CMD bin/kafka-server-start.sh config/server.properties

