FROM python:3.9

WORKDIR /stream

COPY requirements.txt /stream/requirements.txt
#COPY dwh/twitter/api_stream.py /stream/api_stream.py
COPY dwh/ /stream
COPY .env /stream/.env

RUN pip install -r requirements.txt

CMD python streams/twitter_stream.py
