# PORT:2181
FROM openjdk:11.0.11-jdk-oraclelinux7 AS zookeeper

WORKDIR /zookeeper

RUN curl https://downloads.apache.org/kafka/2.8.0/kafka_2.13-2.8.0.tgz --output kafka.tgz

RUN mkdir kafka/
RUN tar -xzf kafka.tgz -C kafka/ --strip-components=1

EXPOSE 2181

WORKDIR /zookeeper/kafka

CMD bin/zookeeper-server-start.sh config/zookeeper.properties

