FROM openjdk:11.0.11-jdk-oraclelinux7 AS connector

WORKDIR /connector

RUN curl https://downloads.apache.org/kafka/2.8.0/kafka_2.13-2.8.0.tgz --output kafka.tgz

RUN mkdir kafka/
RUN tar -xzf kafka.tgz -C kafka/ --strip-components=1

WORKDIR /connector/kafka

RUN rm /connector/kafka/config/connect-standalone.properties

COPY ./kafka_docker/connect-standalone.properties /connector/kafka/config/

RUN mkdir /connector/kafka/connector

COPY ./kafka_docker/connector/mongodb-kafka.tar.gz /connector/kafka/connector/

WORKDIR /connector/kafka/connector

RUN tar -xzf /connector/kafka/connector/mongodb-kafka.tar.gz

RUN rm /connector/kafka/connector/mongodb-kafka.tar.gz

RUN rm /connector/kafka/connector/mongodb-kafka-connect-mongodb-1.5.1/etc/MongoSinkConnector.properties
COPY ./kafka_docker/MongoSinkConnector.properties /connector/kafka/connector/mongodb-kafka-connect-mongodb-1.5.1/etc/

WORKDIR /connector/kafka

CMD bin/connect-standalone.sh config/connect-standalone.properties connector/mongodb-kafka-connect-mongodb-1.5.1/etc/MongoSinkConnector.properties
