
FROM openjdk:11.0.11-jdk-oraclelinux7 AS CONSUMER 

WORKDIR /consumer

RUN curl https://downloads.apache.org/kafka/2.8.0/kafka_2.13-2.8.0.tgz --output kafka.tgz

RUN mkdir kafka/
RUN tar -xzf kafka.tgz -C kafka/ --strip-components=1


WORKDIR /consumer/kafka

CMD bin/kafka-console-consumer.sh --bootstrap-server broker:9092 --topic dataScience --from-beginning

